# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'FROM node:11-alpine  RUN mkdir -p /usr/src/app  WORKDIR /usr/src/app  COPY . .  RUN sed -i &quot;s/mongodb:\/\/localhost/mongodb:\/\/mongo/g&quot; common/services/mongoose.service.js  RUN npm install  EXPOSE 3600  CMD [&quot;npm&quot;, &quot;run&quot;, &quot;start&quot;]'
        tags: |
          $(tag)
